CREATE TABLE "worker_job_outcomes" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "worker_job_outcomes_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"org_id" integer NOT NULL,
	"job_type" text NOT NULL,
	"subject" text NOT NULL,
	"status" text NOT NULL,
	"reason" text,
	"error" text,
	"duration_ms" integer NOT NULL,
	"details" jsonb,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "worker_job_outcomes" ADD CONSTRAINT "worker_job_outcomes_org_id_orgs_id_fk" FOREIGN KEY ("org_id") REFERENCES "public"."orgs"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "worker_job_outcomes_org_type_created" ON "worker_job_outcomes" USING btree ("org_id","job_type","created_at");